// app/employees/page.tsx
'use client'

import { useEffect, useState } from 'react'
import * as Dialog from '@radix-ui/react-dialog'

interface Employee {
    id: number
    name: string
    position: string
    department: string
    email: string
}

export default function EmployeesPage() {
    const [employees, setEmployees] = useState<Employee[]>([])
    const [dialogOpen, setDialogOpen] = useState(false)
    const [formData, setFormData] = useState({
        name: '',
        position: '',
        department: '',
        email: ''
    })

    useEffect(() => {
        fetchEmployees()
    }, [])

    const fetchEmployees = async () => {
        const res = await fetch('/api/employees')
        const data = await res.json()
        if (data.success) setEmployees(data.data)
    }

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault()

        const res = await fetch('/api/employees', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(formData)
        })

        if (res.ok) {
            fetchEmployees()
            setDialogOpen(false)
            setFormData({ name: '', position: '', department: '', email: '' })
        }
    }

    const handleDelete = async (id: number) => {
        if (!confirm('คุณแน่ใจหรือไม่ที่จะลบพนักงานคนนี้?')) return

        const res = await fetch(`/api/employees/${id}`, {
            method: 'DELETE'
        })

        if (res.ok) {
            fetchEmployees()
        }
    }

    return (
        <div className="min-h-screen bg-gray-50">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
                <div className="flex justify-between items-center mb-6">
                    <h1 className="text-3xl font-bold text-gray-900">จัดการพนักงาน</h1>
                    <button
                        onClick={() => setDialogOpen(true)}
                        className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
                    >
                        + เพิ่มพนักงาน
                    </button>
                </div>

                <div className="bg-white rounded-lg shadow overflow-hidden">
                    <div className="overflow-x-auto">
                        <table className="min-w-full divide-y divide-gray-200">
                            <thead className="bg-gray-50">
                                <tr>
                                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        ชื่อ
                                    </th>
                                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        ตำแหน่ง
                                    </th>
                                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        แผนก
                                    </th>
                                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        อีเมล
                                    </th>
                                    <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        การจัดการ
                                    </th>
                                </tr>
                            </thead>
                            <tbody className="bg-white divide-y divide-gray-200">
                                {employees.map((employee) => (
                                    <tr key={employee.id} className="hover:bg-gray-50">
                                        <td className="px-6 py-4 whitespace-nowrap">
                                            <div className="text-sm font-medium text-gray-900">{employee.name}</div>
                                        </td>
                                        <td className="px-6 py-4 whitespace-nowrap">
                                            <div className="text-sm text-gray-900">{employee.position}</div>
                                        </td>
                                        <td className="px-6 py-4 whitespace-nowrap">
                                            <div className="text-sm text-gray-900">{employee.department}</div>
                                        </td>
                                        <td className="px-6 py-4 whitespace-nowrap">
                                            <div className="text-sm text-gray-500">{employee.email}</div>
                                        </td>
                                        <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                            <button
                                                onClick={() => handleDelete(employee.id)}
                                                className="text-red-600 hover:text-red-900"
                                            >
                                                ลบ
                                            </button>
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            {/* Add Employee Dialog */}
            <Dialog.Root open={dialogOpen} onOpenChange={setDialogOpen}>
                <Dialog.Portal>
                    <Dialog.Overlay className="fixed inset-0 bg-black/50 z-50" />
                    <Dialog.Content className="fixed top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 bg-white rounded-lg p-6 w-full max-w-md z-50 shadow-xl">
                        <Dialog.Title className="text-xl font-bold mb-4">เพิ่มพนักงาน</Dialog.Title>

                        <form onSubmit={handleSubmit} className="space-y-4">
                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">
                                    ชื่อ
                                </label>
                                <input
                                    type="text"
                                    value={formData.name}
                                    onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                                    required
                                />
                            </div>

                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">
                                    ตำแหน่ง
                                </label>
                                <input
                                    type="text"
                                    value={formData.position}
                                    onChange={(e) => setFormData({ ...formData, position: e.target.value })}
                                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                                    required
                                />
                            </div>

                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">
                                    แผนก
                                </label>
                                <input
                                    type="text"
                                    value={formData.department}
                                    onChange={(e) => setFormData({ ...formData, department: e.target.value })}
                                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                                    required
                                />
                            </div>

                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">
                                    อีเมล
                                </label>
                                <input
                                    type="email"
                                    value={formData.email}
                                    onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                                    required
                                />
                            </div>

                            <div className="flex justify-end space-x-2 pt-4">
                                <Dialog.Close className="px-4 py-2 bg-gray-200 text-gray-700 rounded-lg hover:bg-gray-300">
                                    ยกเลิก
                                </Dialog.Close>
                                <button
                                    type="submit"
                                    className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
                                >
                                    บันทึก
                                </button>
                            </div>
                        </form>
                    </Dialog.Content>
                </Dialog.Portal>
            </Dialog.Root>
        </div>
    )
}

// app/pages/employees.vue
<template>
    <div class="page-content pa-4">
        <!-- Header -->
        <div class="d-flex justify-space-between align-center mb-6">
            <div>
                <h1 class="text-h5 font-weight-bold text-primary mb-1">จัดการพนักงาน</h1>
                <p class="text-body-2 text-medium-emphasis">รายชื่อและข้อมูลพนักงานทั้งหมด</p>
            </div>
            <v-btn color="primary" prepend-icon="mdi-plus" flat @click="openAddModal">
                เพิ่มพนักงาน
            </v-btn>
        </div>

        <v-card flat class="border rounded-lg overflow-hidden">
            <div class="table-responsive">
                <v-table>
                <thead>
                    <tr class="bg-surface-light">
                        <th class="text-left font-weight-bold">รหัส</th>
                        <th class="text-left font-weight-bold">ชื่อ-นามสกุล</th>
                        <th class="text-left font-weight-bold">ตำแหน่ง</th>
                        <th class="text-left font-weight-bold">แผนก</th>
                        <th class="text-left font-weight-bold">อีเมล</th>
                        <th class="text-right font-weight-bold">จัดการ</th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="employee in employees" :key="employee.id" class="employee-row">
                        <td><span class="text-caption text-medium-emphasis">#{{ employee.id }}</span></td>
                        <td class="font-weight-medium">{{ employee.name }}</td>
                        <td>{{ employee.position }}</td>
                        <td>
                            <v-chip size="small" color="primary" variant="flat" label class="font-weight-medium">
                                {{ employee.department }}
                            </v-chip>
                        </td>
                        <td class="text-body-2 text-medium-emphasis">{{ employee.email }}</td>
                        <td class="text-right">
                            <v-btn icon="mdi-pencil" size="small" variant="text" color="primary" class="mr-1"
                                @click="startEdit(employee)"></v-btn>
                            <v-btn icon="mdi-delete" size="small" variant="text" color="error"
                                @click="deleteEmployee(employee.id)"></v-btn>
                        </td>
                    </tr>
                    <tr v-if="employees.length === 0">
                        <td colspan="6" class="text-center py-8 text-medium-emphasis">
                            ไม่พบข้อมูลพนักงาน
                        </td>
                    </tr>
                </tbody>
            </v-table>
            </div>
        </v-card>

        <!-- Add/Edit Dialog -->
        <v-dialog v-model="isModalOpen" max-width="500" persistent>
            <v-card class="rounded-lg">
                <v-card-title class="d-flex justify-space-between align-center py-3 border-b">
                    <span class="text-h6 font-weight-bold">{{ editingEmployee ? 'แก้ไขข้อมูล' : 'เพิ่มพนักงานใหม่' }}</span>
                    <v-btn icon="mdi-close" variant="text" density="comfortable"
                        @click="closeModal"></v-btn>
                </v-card-title>

                <v-card-text class="pa-5">
                    <v-form @submit.prevent="handleSubmit">
                        <div class="mb-4">
                            <label class="text-caption font-weight-bold mb-1 d-block">ชื่อ-นามสกุล</label>
                            <v-text-field v-model="formData.name" variant="outlined" density="comfortable"
                                hide-details="auto" :rules="[v => !!v || 'กรุณาระบุชื่อ']" required></v-text-field>
                        </div>

                        <div class="mb-4">
                            <label class="text-caption font-weight-bold mb-1 d-block">ตำแหน่ง</label>
                            <v-text-field v-model="formData.position" variant="outlined" density="comfortable"
                                hide-details="auto" required></v-text-field>
                        </div>

                        <div class="mb-4">
                            <label class="text-caption font-weight-bold mb-1 d-block">แผนก</label>
                            <v-text-field v-model="formData.department" variant="outlined" density="comfortable"
                                hide-details="auto" required></v-text-field>
                        </div>

                        <div class="mb-6">
                            <label class="text-caption font-weight-bold mb-1 d-block">อีเมล</label>
                            <v-text-field v-model="formData.email" type="email" variant="outlined" density="comfortable"
                                hide-details="auto" required></v-text-field>
                        </div>

                        <div class="d-flex justify-end gap-2">
                            <v-btn variant="text" class="px-4" @click="closeModal">ยกเลิก</v-btn>
                            <v-btn color="primary" flat class="px-6" type="submit" :loading="submitting">
                                บันทึก
                            </v-btn>
                        </div>
                    </v-form>
                </v-card-text>
            </v-card>
        </v-dialog>
    </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';

useHead({
    title: 'จัดการพนักงาน - ตารางเวรปฏิบัติงาน'
});

interface Employee {
    id: number;
    name: string;
    position: string;
    department: string;
    email: string;
}

const employees = ref<Employee[]>([]);
const isModalOpen = ref(false);
const submitting = ref(false);
const editingEmployee = ref<Employee | null>(null);

const formData = ref({
    name: '',
    position: '',
    department: '',
    email: ''
});

const loadEmployees = async () => {
    try {
        const response = await $fetch('/api/employees');
        employees.value = (response as any).data;
    } catch (error) {
        console.error('Failed to load employees:', error);
    }
};

onMounted(() => {
    loadEmployees();
});

const openAddModal = () => {
    editingEmployee.value = null;
    formData.value = {
        name: '',
        position: '',
        department: '',
        email: ''
    };
    isModalOpen.value = true;
};

const startEdit = (employee: Employee) => {
    editingEmployee.value = employee;
    formData.value = {
        name: employee.name,
        position: employee.position,
        department: employee.department,
        email: employee.email
    };
    isModalOpen.value = true;
};

const closeModal = () => {
    isModalOpen.value = false;
    editingEmployee.value = null;
    formData.value = {
        name: '',
        position: '',
        department: '',
        email: ''
    };
};

const handleSubmit = async () => {
    submitting.value = true;

    try {
        if (editingEmployee.value) {
            await $fetch(`/api/employees/${editingEmployee.value.id}`, {
                method: 'PUT',
                body: formData.value
            });
        } else {
            await $fetch('/api/employees', {
                method: 'POST',
                body: formData.value
            });
        }

        closeModal();
        await loadEmployees();
    } catch (error: any) {
        alert(error.data?.message || 'ไม่สามารถบันทึกข้อมูลได้');
    } finally {
        submitting.value = false;
    }
};

const deleteEmployee = async (id: number) => {
    if (!confirm('ยืนยันลบข้อมูลพนักงานนี้?')) {
        return;
    }

    try {
        await $fetch(`/api/employees/${id}`, {
            method: 'DELETE'
        });
        await loadEmployees();
    } catch (error: any) {
        alert(error.data?.message || 'ไม่สามารถลบข้อมูลได้');
    }
};
</script>

<style scoped>
.gap-2 {
    gap: 8px;
}
.border {
    border: 1px solid #dadce0;
}
.border-b {
    border-bottom: 1px solid #dadce0;
}
.employee-row:hover {
    background-color: #f8f9fa;
}
</style>
